services:
  postgres:
    image: postgres:15-alpine
    container_name: polydoc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: polydoc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data Persist data across container restarts

volumes:
  postgres_data:
